#缺少参数，暂时无法使用

[dataset]
dataset = "SHL"
batch_size = 32
train_file_path = "./data/npy_data/train/data.npy" 
train_label_path = "./data/npy_data/train/label.npy"
test_file_path = "./data/npy_data/test/data.npy"
valid_label_path = "./data/npy_data/valid/label.npy"
valid_file_path = "./data/npy_data/valid/data.npy"
[model]
model = "GoogleNet"
[config]
optim = "Adam"
criterion = "CrossEntropyLoss"
lr = 0.001
epochs = 100

